name: Deploy to development
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  Deploy-Development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

        # fetch the Vercel environment information.
      - name: pull Vercel env info
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

        # this wil set the commit SHA as an environment variable.
      - name: Set commit SHA as an environment variable
        run: echo "NEXT_PUBLIC_COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

        # builds the project. It does the same as: npm run build.
      - name: Build project artifact
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

        # This step deploys the project build to Vercel.
      - name: Deploy project artifacts to Vercel
        id: deploy
        run: echo "URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT

      - name: Alias last deployment
        env:
          URL: ${{ steps.deploy.outputs.URL }}
        run: vercel alias set $URL testing-vercel-jarnes-projects-276e175d --token=${{ secrets.VERCEL_TOKEN }}