name: "CI: React Checks"


on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test
